public class Main {
    public static void main(String[] args) {
        System.out.println(isLeapYear(1984));
    }

    /** This may take some time...
     In next year should update this list */
    public static boolean isLeapYear(int year) {
        if (year ==  0 ) { return true ; }
        if (year == 1 ) { return false ; }
        if (year == 2 ) { return false ; }
        if (year == 3 ) { return false ; }
        if (year == 4 ) { return true ; }
        if (year == 5 ) { return false ; }
        if (year == 6 ) { return false ; }
        if (year == 7 ) { return false ; }
        if (year == 8 ) { return true ; }
        if (year == 9 ) { return false ; }
        if (year == 10 ) { return false ; }
        if (year == 11 ) { return false ; }
        if (year == 12 ) { return true ; }
        if (year == 13 ) { return false ; }
        if (year == 14 ) { return false ; }
        if (year == 15 ) { return false ; }
        if (year == 16 ) { return true ; }
        if (year == 17 ) { return false ; }
        if (year == 18 ) { return false ; }
        if (year == 19 ) { return false ; }
        if (year == 20 ) { return true ; }
        if (year == 21 ) { return false ; }
        if (year == 22 ) { return false ; }
        if (year == 23 ) { return false ; }
        if (year == 24 ) { return true ; }
        if (year == 25 ) { return false ; }
        if (year == 26 ) { return false ; }
        if (year == 27 ) { return false ; }
        if (year == 28 ) { return true ; }
        if (year == 29 ) { return false ; }
        if (year == 30 ) { return false ; }
        if (year == 31 ) { return false ; }
        if (year == 32 ) { return true ; }
        if (year == 33 ) { return false ; }
        if (year == 34 ) { return false ; }
        if (year == 35 ) { return false ; }
        if (year == 36 ) { return true ; }
        if (year == 37 ) { return false ; }
        if (year == 38 ) { return false ; }
        if (year == 39 ) { return false ; }
        if (year == 40 ) { return true ; }
        if (year == 41 ) { return false ; }
        if (year == 42 ) { return false ; }
        if (year == 43 ) { return false ; }
        if (year == 44 ) { return true ; }
        if (year == 45 ) { return false ; }
        if (year == 46 ) { return false ; }
        if (year == 47 ) { return false ; }
        if (year == 48 ) { return true ; }
        if (year == 49 ) { return false ; }
        if (year == 50 ) { return false ; }
        if (year == 51 ) { return false ; }
        if (year == 52 ) { return true ; }
        if (year == 53 ) { return false ; }
        if (year == 54 ) { return false ; }
        if (year == 55 ) { return false ; }
        if (year == 56 ) { return true ; }
        if (year == 57 ) { return false ; }
        if (year == 58 ) { return false ; }
        if (year == 59 ) { return false ; }
        if (year == 60 ) { return true ; }
        if (year == 61 ) { return false ; }
        if (year == 62 ) { return false ; }
        if (year == 63 ) { return false ; }
        if (year == 64 ) { return true ; }
        if (year == 65 ) { return false ; }
        if (year == 66 ) { return false ; }
        if (year == 67 ) { return false ; }
        if (year == 68 ) { return true ; }
        if (year == 69 ) { return false ; }
        if (year == 70 ) { return false ; }
        if (year == 71 ) { return false ; }
        if (year == 72 ) { return true ; }
        if (year == 73 ) { return false ; }
        if (year == 74 ) { return false ; }
        if (year == 75 ) { return false ; }
        if (year == 76 ) { return true ; }
        if (year == 77 ) { return false ; }
        if (year == 78 ) { return false ; }
        if (year == 79 ) { return false ; }
        if (year == 80 ) { return true ; }
        if (year == 81 ) { return false ; }
        if (year == 82 ) { return false ; }
        if (year == 83 ) { return false ; }
        if (year == 84 ) { return true ; }
        if (year == 85 ) { return false ; }
        if (year == 86 ) { return false ; }
        if (year == 87 ) { return false ; }
        if (year == 88 ) { return true ; }
        if (year == 89 ) { return false ; }
        if (year == 90 ) { return false ; }
        if (year == 91 ) { return false ; }
        if (year == 92 ) { return true ; }
        if (year == 93 ) { return false ; }
        if (year == 94 ) { return false ; }
        if (year == 95 ) { return false ; }
        if (year == 96 ) { return true ; }
        if (year == 97 ) { return false ; }
        if (year == 98 ) { return false ; }
        if (year == 99 ) { return false ; }
        if (year == 100 ) { return false ; }
        if (year == 101 ) { return false ; }
        if (year == 102 ) { return false ; }
        if (year == 103 ) { return false ; }
        if (year == 104 ) { return true ; }
        if (year == 105 ) { return false ; }
        if (year == 106 ) { return false ; }
        if (year == 107 ) { return false ; }
        if (year == 108 ) { return true ; }
        if (year == 109 ) { return false ; }
        if (year == 110 ) { return false ; }
        if (year == 111 ) { return false ; }
        if (year == 112 ) { return true ; }
        if (year == 113 ) { return false ; }
        if (year == 114 ) { return false ; }
        if (year == 115 ) { return false ; }
        if (year == 116 ) { return true ; }
        if (year == 117 ) { return false ; }
        if (year == 118 ) { return false ; }
        if (year == 119 ) { return false ; }
        if (year == 120 ) { return true ; }
        if (year == 121 ) { return false ; }
        if (year == 122 ) { return false ; }
        if (year == 123 ) { return false ; }
        if (year == 124 ) { return true ; }
        if (year == 125 ) { return false ; }
        if (year == 126 ) { return false ; }
        if (year == 127 ) { return false ; }
        if (year == 128 ) { return true ; }
        if (year == 129 ) { return false ; }
        if (year == 130 ) { return false ; }
        if (year == 131 ) { return false ; }
        if (year == 132 ) { return true ; }
        if (year == 133 ) { return false ; }
        if (year == 134 ) { return false ; }
        if (year == 135 ) { return false ; }
        if (year == 136 ) { return true ; }
        if (year == 137 ) { return false ; }
        if (year == 138 ) { return false ; }
        if (year == 139 ) { return false ; }
        if (year == 140 ) { return true ; }
        if (year == 141 ) { return false ; }
        if (year == 142 ) { return false ; }
        if (year == 143 ) { return false ; }
        if (year == 144 ) { return true ; }
        if (year == 145 ) { return false ; }
        if (year == 146 ) { return false ; }
        if (year == 147 ) { return false ; }
        if (year == 148 ) { return true ; }
        if (year == 149 ) { return false ; }
        if (year == 150 ) { return false ; }
        if (year == 151 ) { return false ; }
        if (year == 152 ) { return true ; }
        if (year == 153 ) { return false ; }
        if (year == 154 ) { return false ; }
        if (year == 155 ) { return false ; }
        if (year == 156 ) { return true ; }
        if (year == 157 ) { return false ; }
        if (year == 158 ) { return false ; }
        if (year == 159 ) { return false ; }
        if (year == 160 ) { return true ; }
        if (year == 161 ) { return false ; }
        if (year == 162 ) { return false ; }
        if (year == 163 ) { return false ; }
        if (year == 164 ) { return true ; }
        if (year == 165 ) { return false ; }
        if (year == 166 ) { return false ; }
        if (year == 167 ) { return false ; }
        if (year == 168 ) { return true ; }
        if (year == 169 ) { return false ; }
        if (year == 170 ) { return false ; }
        if (year == 171 ) { return false ; }
        if (year == 172 ) { return true ; }
        if (year == 173 ) { return false ; }
        if (year == 174 ) { return false ; }
        if (year == 175 ) { return false ; }
        if (year == 176 ) { return true ; }
        if (year == 177 ) { return false ; }
        if (year == 178 ) { return false ; }
        if (year == 179 ) { return false ; }
        if (year == 180 ) { return true ; }
        if (year == 181 ) { return false ; }
        if (year == 182 ) { return false ; }
        if (year == 183 ) { return false ; }
        if (year == 184 ) { return true ; }
        if (year == 185 ) { return false ; }
        if (year == 186 ) { return false ; }
        if (year == 187 ) { return false ; }
        if (year == 188 ) { return true ; }
        if (year == 189 ) { return false ; }
        if (year == 190 ) { return false ; }
        if (year == 191 ) { return false ; }
        if (year == 192 ) { return true ; }
        if (year == 193 ) { return false ; }
        if (year == 194 ) { return false ; }
        if (year == 195 ) { return false ; }
        if (year == 196 ) { return true ; }
        if (year == 197 ) { return false ; }
        if (year == 198 ) { return false ; }
        if (year == 199 ) { return false ; }
        if (year == 200 ) { return false ; }
        if (year == 201 ) { return false ; }
        if (year == 202 ) { return false ; }
        if (year == 203 ) { return false ; }
        if (year == 204 ) { return true ; }
        if (year == 205 ) { return false ; }
        if (year == 206 ) { return false ; }
        if (year == 207 ) { return false ; }
        if (year == 208 ) { return true ; }
        if (year == 209 ) { return false ; }
        if (year == 210 ) { return false ; }
        if (year == 211 ) { return false ; }
        if (year == 212 ) { return true ; }
        if (year == 213 ) { return false ; }
        if (year == 214 ) { return false ; }
        if (year == 215 ) { return false ; }
        if (year == 216 ) { return true ; }
        if (year == 217 ) { return false ; }
        if (year == 218 ) { return false ; }
        if (year == 219 ) { return false ; }
        if (year == 220 ) { return true ; }
        if (year == 221 ) { return false ; }
        if (year == 222 ) { return false ; }
        if (year == 223 ) { return false ; }
        if (year == 224 ) { return true ; }
        if (year == 225 ) { return false ; }
        if (year == 226 ) { return false ; }
        if (year == 227 ) { return false ; }
        if (year == 228 ) { return true ; }
        if (year == 229 ) { return false ; }
        if (year == 230 ) { return false ; }
        if (year == 231 ) { return false ; }
        if (year == 232 ) { return true ; }
        if (year == 233 ) { return false ; }
        if (year == 234 ) { return false ; }
        if (year == 235 ) { return false ; }
        if (year == 236 ) { return true ; }
        if (year == 237 ) { return false ; }
        if (year == 238 ) { return false ; }
        if (year == 239 ) { return false ; }
        if (year == 240 ) { return true ; }
        if (year == 241 ) { return false ; }
        if (year == 242 ) { return false ; }
        if (year == 243 ) { return false ; }
        if (year == 244 ) { return true ; }
        if (year == 245 ) { return false ; }
        if (year == 246 ) { return false ; }
        if (year == 247 ) { return false ; }
        if (year == 248 ) { return true ; }
        if (year == 249 ) { return false ; }
        if (year == 250 ) { return false ; }
        if (year == 251 ) { return false ; }
        if (year == 252 ) { return true ; }
        if (year == 253 ) { return false ; }
        if (year == 254 ) { return false ; }
        if (year == 255 ) { return false ; }
        if (year == 256 ) { return true ; }
        if (year == 257 ) { return false ; }
        if (year == 258 ) { return false ; }
        if (year == 259 ) { return false ; }
        if (year == 260 ) { return true ; }
        if (year == 261 ) { return false ; }
        if (year == 262 ) { return false ; }
        if (year == 263 ) { return false ; }
        if (year == 264 ) { return true ; }
        if (year == 265 ) { return false ; }
        if (year == 266 ) { return false ; }
        if (year == 267 ) { return false ; }
        if (year == 268 ) { return true ; }
        if (year == 269 ) { return false ; }
        if (year == 270 ) { return false ; }
        if (year == 271 ) { return false ; }
        if (year == 272 ) { return true ; }
        if (year == 273 ) { return false ; }
        if (year == 274 ) { return false ; }
        if (year == 275 ) { return false ; }
        if (year == 276 ) { return true ; }
        if (year == 277 ) { return false ; }
        if (year == 278 ) { return false ; }
        if (year == 279 ) { return false ; }
        if (year == 280 ) { return true ; }
        if (year == 281 ) { return false ; }
        if (year == 282 ) { return false ; }
        if (year == 283 ) { return false ; }
        if (year == 284 ) { return true ; }
        if (year == 285 ) { return false ; }
        if (year == 286 ) { return false ; }
        if (year == 287 ) { return false ; }
        if (year == 288 ) { return true ; }
        if (year == 289 ) { return false ; }
        if (year == 290 ) { return false ; }
        if (year == 291 ) { return false ; }
        if (year == 292 ) { return true ; }
        if (year == 293 ) { return false ; }
        if (year == 294 ) { return false ; }
        if (year == 295 ) { return false ; }
        if (year == 296 ) { return true ; }
        if (year == 297 ) { return false ; }
        if (year == 298 ) { return false ; }
        if (year == 299 ) { return false ; }
        if (year == 300 ) { return false ; }
        if (year == 301 ) { return false ; }
        if (year == 302 ) { return false ; }
        if (year == 303 ) { return false ; }
        if (year == 304 ) { return true ; }
        if (year == 305 ) { return false ; }
        if (year == 306 ) { return false ; }
        if (year == 307 ) { return false ; }
        if (year == 308 ) { return true ; }
        if (year == 309 ) { return false ; }
        if (year == 310 ) { return false ; }
        if (year == 311 ) { return false ; }
        if (year == 312 ) { return true ; }
        if (year == 313 ) { return false ; }
        if (year == 314 ) { return false ; }
        if (year == 315 ) { return false ; }
        if (year == 316 ) { return true ; }
        if (year == 317 ) { return false ; }
        if (year == 318 ) { return false ; }
        if (year == 319 ) { return false ; }
        if (year == 320 ) { return true ; }
        if (year == 321 ) { return false ; }
        if (year == 322 ) { return false ; }
        if (year == 323 ) { return false ; }
        if (year == 324 ) { return true ; }
        if (year == 325 ) { return false ; }
        if (year == 326 ) { return false ; }
        if (year == 327 ) { return false ; }
        if (year == 328 ) { return true ; }
        if (year == 329 ) { return false ; }
        if (year == 330 ) { return false ; }
        if (year == 331 ) { return false ; }
        if (year == 332 ) { return true ; }
        if (year == 333 ) { return false ; }
        if (year == 334 ) { return false ; }
        if (year == 335 ) { return false ; }
        if (year == 336 ) { return true ; }
        if (year == 337 ) { return false ; }
        if (year == 338 ) { return false ; }
        if (year == 339 ) { return false ; }
        if (year == 340 ) { return true ; }
        if (year == 341 ) { return false ; }
        if (year == 342 ) { return false ; }
        if (year == 343 ) { return false ; }
        if (year == 344 ) { return true ; }
        if (year == 345 ) { return false ; }
        if (year == 346 ) { return false ; }
        if (year == 347 ) { return false ; }
        if (year == 348 ) { return true ; }
        if (year == 349 ) { return false ; }
        if (year == 350 ) { return false ; }
        if (year == 351 ) { return false ; }
        if (year == 352 ) { return true ; }
        if (year == 353 ) { return false ; }
        if (year == 354 ) { return false ; }
        if (year == 355 ) { return false ; }
        if (year == 356 ) { return true ; }
        if (year == 357 ) { return false ; }
        if (year == 358 ) { return false ; }
        if (year == 359 ) { return false ; }
        if (year == 360 ) { return true ; }
        if (year == 361 ) { return false ; }
        if (year == 362 ) { return false ; }
        if (year == 363 ) { return false ; }
        if (year == 364 ) { return true ; }
        if (year == 365 ) { return false ; }
        if (year == 366 ) { return false ; }
        if (year == 367 ) { return false ; }
        if (year == 368 ) { return true ; }
        if (year == 369 ) { return false ; }
        if (year == 370 ) { return false ; }
        if (year == 371 ) { return false ; }
        if (year == 372 ) { return true ; }
        if (year == 373 ) { return false ; }
        if (year == 374 ) { return false ; }
        if (year == 375 ) { return false ; }
        if (year == 376 ) { return true ; }
        if (year == 377 ) { return false ; }
        if (year == 378 ) { return false ; }
        if (year == 379 ) { return false ; }
        if (year == 380 ) { return true ; }
        if (year == 381 ) { return false ; }
        if (year == 382 ) { return false ; }
        if (year == 383 ) { return false ; }
        if (year == 384 ) { return true ; }
        if (year == 385 ) { return false ; }
        if (year == 386 ) { return false ; }
        if (year == 387 ) { return false ; }
        if (year == 388 ) { return true ; }
        if (year == 389 ) { return false ; }
        if (year == 390 ) { return false ; }
        if (year == 391 ) { return false ; }
        if (year == 392 ) { return true ; }
        if (year == 393 ) { return false ; }
        if (year == 394 ) { return false ; }
        if (year == 395 ) { return false ; }
        if (year == 396 ) { return true ; }
        if (year == 397 ) { return false ; }
        if (year == 398 ) { return false ; }
        if (year == 399 ) { return false ; }
        if (year == 400 ) { return true ; }
        if (year == 401 ) { return false ; }
        if (year == 402 ) { return false ; }
        if (year == 403 ) { return false ; }
        if (year == 404 ) { return true ; }
        if (year == 405 ) { return false ; }
        if (year == 406 ) { return false ; }
        if (year == 407 ) { return false ; }
        if (year == 408 ) { return true ; }
        if (year == 409 ) { return false ; }
        if (year == 410 ) { return false ; }
        if (year == 411 ) { return false ; }
        if (year == 412 ) { return true ; }
        if (year == 413 ) { return false ; }
        if (year == 414 ) { return false ; }
        if (year == 415 ) { return false ; }
        if (year == 416 ) { return true ; }
        if (year == 417 ) { return false ; }
        if (year == 418 ) { return false ; }
        if (year == 419 ) { return false ; }
        if (year == 420 ) { return true ; }
        if (year == 421 ) { return false ; }
        if (year == 422 ) { return false ; }
        if (year == 423 ) { return false ; }
        if (year == 424 ) { return true ; }
        if (year == 425 ) { return false ; }
        if (year == 426 ) { return false ; }
        if (year == 427 ) { return false ; }
        if (year == 428 ) { return true ; }
        if (year == 429 ) { return false ; }
        if (year == 430 ) { return false ; }
        if (year == 431 ) { return false ; }
        if (year == 432 ) { return true ; }
        if (year == 433 ) { return false ; }
        if (year == 434 ) { return false ; }
        if (year == 435 ) { return false ; }
        if (year == 436 ) { return true ; }
        if (year == 437 ) { return false ; }
        if (year == 438 ) { return false ; }
        if (year == 439 ) { return false ; }
        if (year == 440 ) { return true ; }
        if (year == 441 ) { return false ; }
        if (year == 442 ) { return false ; }
        if (year == 443 ) { return false ; }
        if (year == 444 ) { return true ; }
        if (year == 445 ) { return false ; }
        if (year == 446 ) { return false ; }
        if (year == 447 ) { return false ; }
        if (year == 448 ) { return true ; }
        if (year == 449 ) { return false ; }
        if (year == 450 ) { return false ; }
        if (year == 451 ) { return false ; }
        if (year == 452 ) { return true ; }
        if (year == 453 ) { return false ; }
        if (year == 454 ) { return false ; }
        if (year == 455 ) { return false ; }
        if (year == 456 ) { return true ; }
        if (year == 457 ) { return false ; }
        if (year == 458 ) { return false ; }
        if (year == 459 ) { return false ; }
        if (year == 460 ) { return true ; }
        if (year == 461 ) { return false ; }
        if (year == 462 ) { return false ; }
        if (year == 463 ) { return false ; }
        if (year == 464 ) { return true ; }
        if (year == 465 ) { return false ; }
        if (year == 466 ) { return false ; }
        if (year == 467 ) { return false ; }
        if (year == 468 ) { return true ; }
        if (year == 469 ) { return false ; }
        if (year == 470 ) { return false ; }
        if (year == 471 ) { return false ; }
        if (year == 472 ) { return true ; }
        if (year == 473 ) { return false ; }
        if (year == 474 ) { return false ; }
        if (year == 475 ) { return false ; }
        if (year == 476 ) { return true ; }
        if (year == 477 ) { return false ; }
        if (year == 478 ) { return false ; }
        if (year == 479 ) { return false ; }
        if (year == 480 ) { return true ; }
        if (year == 481 ) { return false ; }
        if (year == 482 ) { return false ; }
        if (year == 483 ) { return false ; }
        if (year == 484 ) { return true ; }
        if (year == 485 ) { return false ; }
        if (year == 486 ) { return false ; }
        if (year == 487 ) { return false ; }
        if (year == 488 ) { return true ; }
        if (year == 489 ) { return false ; }
        if (year == 490 ) { return false ; }
        if (year == 491 ) { return false ; }
        if (year == 492 ) { return true ; }
        if (year == 493 ) { return false ; }
        if (year == 494 ) { return false ; }
        if (year == 495 ) { return false ; }
        if (year == 496 ) { return true ; }
        if (year == 497 ) { return false ; }
        if (year == 498 ) { return false ; }
        if (year == 499 ) { return false ; }
        if (year == 500 ) { return false ; }
        if (year == 501 ) { return false ; }
        if (year == 502 ) { return false ; }
        if (year == 503 ) { return false ; }
        if (year == 504 ) { return true ; }
        if (year == 505 ) { return false ; }
        if (year == 506 ) { return false ; }
        if (year == 507 ) { return false ; }
        if (year == 508 ) { return true ; }
        if (year == 509 ) { return false ; }
        if (year == 510 ) { return false ; }
        if (year == 511 ) { return false ; }
        if (year == 512 ) { return true ; }
        if (year == 513 ) { return false ; }
        if (year == 514 ) { return false ; }
        if (year == 515 ) { return false ; }
        if (year == 516 ) { return true ; }
        if (year == 517 ) { return false ; }
        if (year == 518 ) { return false ; }
        if (year == 519 ) { return false ; }
        if (year == 520 ) { return true ; }
        if (year == 521 ) { return false ; }
        if (year == 522 ) { return false ; }
        if (year == 523 ) { return false ; }
        if (year == 524 ) { return true ; }
        if (year == 525 ) { return false ; }
        if (year == 526 ) { return false ; }
        if (year == 527 ) { return false ; }
        if (year == 528 ) { return true ; }
        if (year == 529 ) { return false ; }
        if (year == 530 ) { return false ; }
        if (year == 531 ) { return false ; }
        if (year == 532 ) { return true ; }
        if (year == 533 ) { return false ; }
        if (year == 534 ) { return false ; }
        if (year == 535 ) { return false ; }
        if (year == 536 ) { return true ; }
        if (year == 537 ) { return false ; }
        if (year == 538 ) { return false ; }
        if (year == 539 ) { return false ; }
        if (year == 540 ) { return true ; }
        if (year == 541 ) { return false ; }
        if (year == 542 ) { return false ; }
        if (year == 543 ) { return false ; }
        if (year == 544 ) { return true ; }
        if (year == 545 ) { return false ; }
        if (year == 546 ) { return false ; }
        if (year == 547 ) { return false ; }
        if (year == 548 ) { return true ; }
        if (year == 549 ) { return false ; }
        if (year == 550 ) { return false ; }
        if (year == 551 ) { return false ; }
        if (year == 552 ) { return true ; }
        if (year == 553 ) { return false ; }
        if (year == 554 ) { return false ; }
        if (year == 555 ) { return false ; }
        if (year == 556 ) { return true ; }
        if (year == 557 ) { return false ; }
        if (year == 558 ) { return false ; }
        if (year == 559 ) { return false ; }
        if (year == 560 ) { return true ; }
        if (year == 561 ) { return false ; }
        if (year == 562 ) { return false ; }
        if (year == 563 ) { return false ; }
        if (year == 564 ) { return true ; }
        if (year == 565 ) { return false ; }
        if (year == 566 ) { return false ; }
        if (year == 567 ) { return false ; }
        if (year == 568 ) { return true ; }
        if (year == 569 ) { return false ; }
        if (year == 570 ) { return false ; }
        if (year == 571 ) { return false ; }
        if (year == 572 ) { return true ; }
        if (year == 573 ) { return false ; }
        if (year == 574 ) { return false ; }
        if (year == 575 ) { return false ; }
        if (year == 576 ) { return true ; }
        if (year == 577 ) { return false ; }
        if (year == 578 ) { return false ; }
        if (year == 579 ) { return false ; }
        if (year == 580 ) { return true ; }
        if (year == 581 ) { return false ; }
        if (year == 582 ) { return false ; }
        if (year == 583 ) { return false ; }
        if (year == 584 ) { return true ; }
        if (year == 585 ) { return false ; }
        if (year == 586 ) { return false ; }
        if (year == 587 ) { return false ; }
        if (year == 588 ) { return true ; }
        if (year == 589 ) { return false ; }
        if (year == 590 ) { return false ; }
        if (year == 591 ) { return false ; }
        if (year == 592 ) { return true ; }
        if (year == 593 ) { return false ; }
        if (year == 594 ) { return false ; }
        if (year == 595 ) { return false ; }
        if (year == 596 ) { return true ; }
        if (year == 597 ) { return false ; }
        if (year == 598 ) { return false ; }
        if (year == 599 ) { return false ; }
        if (year == 600 ) { return false ; }
        if (year == 601 ) { return false ; }
        if (year == 602 ) { return false ; }
        if (year == 603 ) { return false ; }
        if (year == 604 ) { return true ; }
        if (year == 605 ) { return false ; }
        if (year == 606 ) { return false ; }
        if (year == 607 ) { return false ; }
        if (year == 608 ) { return true ; }
        if (year == 609 ) { return false ; }
        if (year == 610 ) { return false ; }
        if (year == 611 ) { return false ; }
        if (year == 612 ) { return true ; }
        if (year == 613 ) { return false ; }
        if (year == 614 ) { return false ; }
        if (year == 615 ) { return false ; }
        if (year == 616 ) { return true ; }
        if (year == 617 ) { return false ; }
        if (year == 618 ) { return false ; }
        if (year == 619 ) { return false ; }
        if (year == 620 ) { return true ; }
        if (year == 621 ) { return false ; }
        if (year == 622 ) { return false ; }
        if (year == 623 ) { return false ; }
        if (year == 624 ) { return true ; }
        if (year == 625 ) { return false ; }
        if (year == 626 ) { return false ; }
        if (year == 627 ) { return false ; }
        if (year == 628 ) { return true ; }
        if (year == 629 ) { return false ; }
        if (year == 630 ) { return false ; }
        if (year == 631 ) { return false ; }
        if (year == 632 ) { return true ; }
        if (year == 633 ) { return false ; }
        if (year == 634 ) { return false ; }
        if (year == 635 ) { return false ; }
        if (year == 636 ) { return true ; }
        if (year == 637 ) { return false ; }
        if (year == 638 ) { return false ; }
        if (year == 639 ) { return false ; }
        if (year == 640 ) { return true ; }
        if (year == 641 ) { return false ; }
        if (year == 642 ) { return false ; }
        if (year == 643 ) { return false ; }
        if (year == 644 ) { return true ; }
        if (year == 645 ) { return false ; }
        if (year == 646 ) { return false ; }
        if (year == 647 ) { return false ; }
        if (year == 648 ) { return true ; }
        if (year == 649 ) { return false ; }
        if (year == 650 ) { return false ; }
        if (year == 651 ) { return false ; }
        if (year == 652 ) { return true ; }
        if (year == 653 ) { return false ; }
        if (year == 654 ) { return false ; }
        if (year == 655 ) { return false ; }
        if (year == 656 ) { return true ; }
        if (year == 657 ) { return false ; }
        if (year == 658 ) { return false ; }
        if (year == 659 ) { return false ; }
        if (year == 660 ) { return true ; }
        if (year == 661 ) { return false ; }
        if (year == 662 ) { return false ; }
        if (year == 663 ) { return false ; }
        if (year == 664 ) { return true ; }
        if (year == 665 ) { return false ; }
        if (year == 666 ) { return false ; }
        if (year == 667 ) { return false ; }
        if (year == 668 ) { return true ; }
        if (year == 669 ) { return false ; }
        if (year == 670 ) { return false ; }
        if (year == 671 ) { return false ; }
        if (year == 672 ) { return true ; }
        if (year == 673 ) { return false ; }
        if (year == 674 ) { return false ; }
        if (year == 675 ) { return false ; }
        if (year == 676 ) { return true ; }
        if (year == 677 ) { return false ; }
        if (year == 678 ) { return false ; }
        if (year == 679 ) { return false ; }
        if (year == 680 ) { return true ; }
        if (year == 681 ) { return false ; }
        if (year == 682 ) { return false ; }
        if (year == 683 ) { return false ; }
        if (year == 684 ) { return true ; }
        if (year == 685 ) { return false ; }
        if (year == 686 ) { return false ; }
        if (year == 687 ) { return false ; }
        if (year == 688 ) { return true ; }
        if (year == 689 ) { return false ; }
        if (year == 690 ) { return false ; }
        if (year == 691 ) { return false ; }
        if (year == 692 ) { return true ; }
        if (year == 693 ) { return false ; }
        if (year == 694 ) { return false ; }
        if (year == 695 ) { return false ; }
        if (year == 696 ) { return true ; }
        if (year == 697 ) { return false ; }
        if (year == 698 ) { return false ; }
        if (year == 699 ) { return false ; }
        if (year == 700 ) { return false ; }
        if (year == 701 ) { return false ; }
        if (year == 702 ) { return false ; }
        if (year == 703 ) { return false ; }
        if (year == 704 ) { return true ; }
        if (year == 705 ) { return false ; }
        if (year == 706 ) { return false ; }
        if (year == 707 ) { return false ; }
        if (year == 708 ) { return true ; }
        if (year == 709 ) { return false ; }
        if (year == 710 ) { return false ; }
        if (year == 711 ) { return false ; }
        if (year == 712 ) { return true ; }
        if (year == 713 ) { return false ; }
        if (year == 714 ) { return false ; }
        if (year == 715 ) { return false ; }
        if (year == 716 ) { return true ; }
        if (year == 717 ) { return false ; }
        if (year == 718 ) { return false ; }
        if (year == 719 ) { return false ; }
        if (year == 720 ) { return true ; }
        if (year == 721 ) { return false ; }
        if (year == 722 ) { return false ; }
        if (year == 723 ) { return false ; }
        if (year == 724 ) { return true ; }
        if (year == 725 ) { return false ; }
        if (year == 726 ) { return false ; }
        if (year == 727 ) { return false ; }
        if (year == 728 ) { return true ; }
        if (year == 729 ) { return false ; }
        if (year == 730 ) { return false ; }
        if (year == 731 ) { return false ; }
        if (year == 732 ) { return true ; }
        if (year == 733 ) { return false ; }
        if (year == 734 ) { return false ; }
        if (year == 735 ) { return false ; }
        if (year == 736 ) { return true ; }
        if (year == 737 ) { return false ; }
        if (year == 738 ) { return false ; }
        if (year == 739 ) { return false ; }
        if (year == 740 ) { return true ; }
        if (year == 741 ) { return false ; }
        if (year == 742 ) { return false ; }
        if (year == 743 ) { return false ; }
        if (year == 744 ) { return true ; }
        if (year == 745 ) { return false ; }
        if (year == 746 ) { return false ; }
        if (year == 747 ) { return false ; }
        if (year == 748 ) { return true ; }
        if (year == 749 ) { return false ; }
        if (year == 750 ) { return false ; }
        if (year == 751 ) { return false ; }
        if (year == 752 ) { return true ; }
        if (year == 753 ) { return false ; }
        if (year == 754 ) { return false ; }
        if (year == 755 ) { return false ; }
        if (year == 756 ) { return true ; }
        if (year == 757 ) { return false ; }
        if (year == 758 ) { return false ; }
        if (year == 759 ) { return false ; }
        if (year == 760 ) { return true ; }
        if (year == 761 ) { return false ; }
        if (year == 762 ) { return false ; }
        if (year == 763 ) { return false ; }
        if (year == 764 ) { return true ; }
        if (year == 765 ) { return false ; }
        if (year == 766 ) { return false ; }
        if (year == 767 ) { return false ; }
        if (year == 768 ) { return true ; }
        if (year == 769 ) { return false ; }
        if (year == 770 ) { return false ; }
        if (year == 771 ) { return false ; }
        if (year == 772 ) { return true ; }
        if (year == 773 ) { return false ; }
        if (year == 774 ) { return false ; }
        if (year == 775 ) { return false ; }
        if (year == 776 ) { return true ; }
        if (year == 777 ) { return false ; }
        if (year == 778 ) { return false ; }
        if (year == 779 ) { return false ; }
        if (year == 780 ) { return true ; }
        if (year == 781 ) { return false ; }
        if (year == 782 ) { return false ; }
        if (year == 783 ) { return false ; }
        if (year == 784 ) { return true ; }
        if (year == 785 ) { return false ; }
        if (year == 786 ) { return false ; }
        if (year == 787 ) { return false ; }
        if (year == 788 ) { return true ; }
        if (year == 789 ) { return false ; }
        if (year == 790 ) { return false ; }
        if (year == 791 ) { return false ; }
        if (year == 792 ) { return true ; }
        if (year == 793 ) { return false ; }
        if (year == 794 ) { return false ; }
        if (year == 795 ) { return false ; }
        if (year == 796 ) { return true ; }
        if (year == 797 ) { return false ; }
        if (year == 798 ) { return false ; }
        if (year == 799 ) { return false ; }
        if (year == 800 ) { return true ; }
        if (year == 801 ) { return false ; }
        if (year == 802 ) { return false ; }
        if (year == 803 ) { return false ; }
        if (year == 804 ) { return true ; }
        if (year == 805 ) { return false ; }
        if (year == 806 ) { return false ; }
        if (year == 807 ) { return false ; }
        if (year == 808 ) { return true ; }
        if (year == 809 ) { return false ; }
        if (year == 810 ) { return false ; }
        if (year == 811 ) { return false ; }
        if (year == 812 ) { return true ; }
        if (year == 813 ) { return false ; }
        if (year == 814 ) { return false ; }
        if (year == 815 ) { return false ; }
        if (year == 816 ) { return true ; }
        if (year == 817 ) { return false ; }
        if (year == 818 ) { return false ; }
        if (year == 819 ) { return false ; }
        if (year == 820 ) { return true ; }
        if (year == 821 ) { return false ; }
        if (year == 822 ) { return false ; }
        if (year == 823 ) { return false ; }
        if (year == 824 ) { return true ; }
        if (year == 825 ) { return false ; }
        if (year == 826 ) { return false ; }
        if (year == 827 ) { return false ; }
        if (year == 828 ) { return true ; }
        if (year == 829 ) { return false ; }
        if (year == 830 ) { return false ; }
        if (year == 831 ) { return false ; }
        if (year == 832 ) { return true ; }
        if (year == 833 ) { return false ; }
        if (year == 834 ) { return false ; }
        if (year == 835 ) { return false ; }
        if (year == 836 ) { return true ; }
        if (year == 837 ) { return false ; }
        if (year == 838 ) { return false ; }
        if (year == 839 ) { return false ; }
        if (year == 840 ) { return true ; }
        if (year == 841 ) { return false ; }
        if (year == 842 ) { return false ; }
        if (year == 843 ) { return false ; }
        if (year == 844 ) { return true ; }
        if (year == 845 ) { return false ; }
        if (year == 846 ) { return false ; }
        if (year == 847 ) { return false ; }
        if (year == 848 ) { return true ; }
        if (year == 849 ) { return false ; }
        if (year == 850 ) { return false ; }
        if (year == 851 ) { return false ; }
        if (year == 852 ) { return true ; }
        if (year == 853 ) { return false ; }
        if (year == 854 ) { return false ; }
        if (year == 855 ) { return false ; }
        if (year == 856 ) { return true ; }
        if (year == 857 ) { return false ; }
        if (year == 858 ) { return false ; }
        if (year == 859 ) { return false ; }
        if (year == 860 ) { return true ; }
        if (year == 861 ) { return false ; }
        if (year == 862 ) { return false ; }
        if (year == 863 ) { return false ; }
        if (year == 864 ) { return true ; }
        if (year == 865 ) { return false ; }
        if (year == 866 ) { return false ; }
        if (year == 867 ) { return false ; }
        if (year == 868 ) { return true ; }
        if (year == 869 ) { return false ; }
        if (year == 870 ) { return false ; }
        if (year == 871 ) { return false ; }
        if (year == 872 ) { return true ; }
        if (year == 873 ) { return false ; }
        if (year == 874 ) { return false ; }
        if (year == 875 ) { return false ; }
        if (year == 876 ) { return true ; }
        if (year == 877 ) { return false ; }
        if (year == 878 ) { return false ; }
        if (year == 879 ) { return false ; }
        if (year == 880 ) { return true ; }
        if (year == 881 ) { return false ; }
        if (year == 882 ) { return false ; }
        if (year == 883 ) { return false ; }
        if (year == 884 ) { return true ; }
        if (year == 885 ) { return false ; }
        if (year == 886 ) { return false ; }
        if (year == 887 ) { return false ; }
        if (year == 888 ) { return true ; }
        if (year == 889 ) { return false ; }
        if (year == 890 ) { return false ; }
        if (year == 891 ) { return false ; }
        if (year == 892 ) { return true ; }
        if (year == 893 ) { return false ; }
        if (year == 894 ) { return false ; }
        if (year == 895 ) { return false ; }
        if (year == 896 ) { return true ; }
        if (year == 897 ) { return false ; }
        if (year == 898 ) { return false ; }
        if (year == 899 ) { return false ; }
        if (year == 900 ) { return false ; }
        if (year == 901 ) { return false ; }
        if (year == 902 ) { return false ; }
        if (year == 903 ) { return false ; }
        if (year == 904 ) { return true ; }
        if (year == 905 ) { return false ; }
        if (year == 906 ) { return false ; }
        if (year == 907 ) { return false ; }
        if (year == 908 ) { return true ; }
        if (year == 909 ) { return false ; }
        if (year == 910 ) { return false ; }
        if (year == 911 ) { return false ; }
        if (year == 912 ) { return true ; }
        if (year == 913 ) { return false ; }
        if (year == 914 ) { return false ; }
        if (year == 915 ) { return false ; }
        if (year == 916 ) { return true ; }
        if (year == 917 ) { return false ; }
        if (year == 918 ) { return false ; }
        if (year == 919 ) { return false ; }
        if (year == 920 ) { return true ; }
        if (year == 921 ) { return false ; }
        if (year == 922 ) { return false ; }
        if (year == 923 ) { return false ; }
        if (year == 924 ) { return true ; }
        if (year == 925 ) { return false ; }
        if (year == 926 ) { return false ; }
        if (year == 927 ) { return false ; }
        if (year == 928 ) { return true ; }
        if (year == 929 ) { return false ; }
        if (year == 930 ) { return false ; }
        if (year == 931 ) { return false ; }
        if (year == 932 ) { return true ; }
        if (year == 933 ) { return false ; }
        if (year == 934 ) { return false ; }
        if (year == 935 ) { return false ; }
        if (year == 936 ) { return true ; }
        if (year == 937 ) { return false ; }
        if (year == 938 ) { return false ; }
        if (year == 939 ) { return false ; }
        if (year == 940 ) { return true ; }
        if (year == 941 ) { return false ; }
        if (year == 942 ) { return false ; }
        if (year == 943 ) { return false ; }
        if (year == 944 ) { return true ; }
        if (year == 945 ) { return false ; }
        if (year == 946 ) { return false ; }
        if (year == 947 ) { return false ; }
        if (year == 948 ) { return true ; }
        if (year == 949 ) { return false ; }
        if (year == 950 ) { return false ; }
        if (year == 951 ) { return false ; }
        if (year == 952 ) { return true ; }
        if (year == 953 ) { return false ; }
        if (year == 954 ) { return false ; }
        if (year == 955 ) { return false ; }
        if (year == 956 ) { return true ; }
        if (year == 957 ) { return false ; }
        if (year == 958 ) { return false ; }
        if (year == 959 ) { return false ; }
        if (year == 960 ) { return true ; }
        if (year == 961 ) { return false ; }
        if (year == 962 ) { return false ; }
        if (year == 963 ) { return false ; }
        if (year == 964 ) { return true ; }
        if (year == 965 ) { return false ; }
        if (year == 966 ) { return false ; }
        if (year == 967 ) { return false ; }
        if (year == 968 ) { return true ; }
        if (year == 969 ) { return false ; }
        if (year == 970 ) { return false ; }
        if (year == 971 ) { return false ; }
        if (year == 972 ) { return true ; }
        if (year == 973 ) { return false ; }
        if (year == 974 ) { return false ; }
        if (year == 975 ) { return false ; }
        if (year == 976 ) { return true ; }
        if (year == 977 ) { return false ; }
        if (year == 978 ) { return false ; }
        if (year == 979 ) { return false ; }
        if (year == 980 ) { return true ; }
        if (year == 981 ) { return false ; }
        if (year == 982 ) { return false ; }
        if (year == 983 ) { return false ; }
        if (year == 984 ) { return true ; }
        if (year == 985 ) { return false ; }
        if (year == 986 ) { return false ; }
        if (year == 987 ) { return false ; }
        if (year == 988 ) { return true ; }
        if (year == 989 ) { return false ; }
        if (year == 990 ) { return false ; }
        if (year == 991 ) { return false ; }
        if (year == 992 ) { return true ; }
        if (year == 993 ) { return false ; }
        if (year == 994 ) { return false ; }
        if (year == 995 ) { return false ; }
        if (year == 996 ) { return true ; }
        if (year == 997 ) { return false ; }
        if (year == 998 ) { return false ; }
        if (year == 999 ) { return false ; }
        if (year == 1000 ) { return false ; }
        if (year == 1001 ) { return false ; }
        if (year == 1002 ) { return false ; }
        if (year == 1003 ) { return false ; }
        if (year == 1004 ) { return true ; }
        if (year == 1005 ) { return false ; }
        if (year == 1006 ) { return false ; }
        if (year == 1007 ) { return false ; }
        if (year == 1008 ) { return true ; }
        if (year == 1009 ) { return false ; }
        if (year == 1010 ) { return false ; }
        if (year == 1011 ) { return false ; }
        if (year == 1012 ) { return true ; }
        if (year == 1013 ) { return false ; }
        if (year == 1014 ) { return false ; }
        if (year == 1015 ) { return false ; }
        if (year == 1016 ) { return true ; }
        if (year == 1017 ) { return false ; }
        if (year == 1018 ) { return false ; }
        if (year == 1019 ) { return false ; }
        if (year == 1020 ) { return true ; }
        if (year == 1021 ) { return false ; }
        if (year == 1022 ) { return false ; }
        if (year == 1023 ) { return false ; }
        if (year == 1024 ) { return true ; }
        if (year == 1025 ) { return false ; }
        if (year == 1026 ) { return false ; }
        if (year == 1027 ) { return false ; }
        if (year == 1028 ) { return true ; }
        if (year == 1029 ) { return false ; }
        if (year == 1030 ) { return false ; }
        if (year == 1031 ) { return false ; }
        if (year == 1032 ) { return true ; }
        if (year == 1033 ) { return false ; }
        if (year == 1034 ) { return false ; }
        if (year == 1035 ) { return false ; }
        if (year == 1036 ) { return true ; }
        if (year == 1037 ) { return false ; }
        if (year == 1038 ) { return false ; }
        if (year == 1039 ) { return false ; }
        if (year == 1040 ) { return true ; }
        if (year == 1041 ) { return false ; }
        if (year == 1042 ) { return false ; }
        if (year == 1043 ) { return false ; }
        if (year == 1044 ) { return true ; }
        if (year == 1045 ) { return false ; }
        if (year == 1046 ) { return false ; }
        if (year == 1047 ) { return false ; }
        if (year == 1048 ) { return true ; }
        if (year == 1049 ) { return false ; }
        if (year == 1050 ) { return false ; }
        if (year == 1051 ) { return false ; }
        if (year == 1052 ) { return true ; }
        if (year == 1053 ) { return false ; }
        if (year == 1054 ) { return false ; }
        if (year == 1055 ) { return false ; }
        if (year == 1056 ) { return true ; }
        if (year == 1057 ) { return false ; }
        if (year == 1058 ) { return false ; }
        if (year == 1059 ) { return false ; }
        if (year == 1060 ) { return true ; }
        if (year == 1061 ) { return false ; }
        if (year == 1062 ) { return false ; }
        if (year == 1063 ) { return false ; }
        if (year == 1064 ) { return true ; }
        if (year == 1065 ) { return false ; }
        if (year == 1066 ) { return false ; }
        if (year == 1067 ) { return false ; }
        if (year == 1068 ) { return true ; }
        if (year == 1069 ) { return false ; }
        if (year == 1070 ) { return false ; }
        if (year == 1071 ) { return false ; }
        if (year == 1072 ) { return true ; }
        if (year == 1073 ) { return false ; }
        if (year == 1074 ) { return false ; }
        if (year == 1075 ) { return false ; }
        if (year == 1076 ) { return true ; }
        if (year == 1077 ) { return false ; }
        if (year == 1078 ) { return false ; }
        if (year == 1079 ) { return false ; }
        if (year == 1080 ) { return true ; }
        if (year == 1081 ) { return false ; }
        if (year == 1082 ) { return false ; }
        if (year == 1083 ) { return false ; }
        if (year == 1084 ) { return true ; }
        if (year == 1085 ) { return false ; }
        if (year == 1086 ) { return false ; }
        if (year == 1087 ) { return false ; }
        if (year == 1088 ) { return true ; }
        if (year == 1089 ) { return false ; }
        if (year == 1090 ) { return false ; }
        if (year == 1091 ) { return false ; }
        if (year == 1092 ) { return true ; }
        if (year == 1093 ) { return false ; }
        if (year == 1094 ) { return false ; }
        if (year == 1095 ) { return false ; }
        if (year == 1096 ) { return true ; }
        if (year == 1097 ) { return false ; }
        if (year == 1098 ) { return false ; }
        if (year == 1099 ) { return false ; }
        if (year == 1100 ) { return false ; }
        if (year == 1101 ) { return false ; }
        if (year == 1102 ) { return false ; }
        if (year == 1103 ) { return false ; }
        if (year == 1104 ) { return true ; }
        if (year == 1105 ) { return false ; }
        if (year == 1106 ) { return false ; }
        if (year == 1107 ) { return false ; }
        if (year == 1108 ) { return true ; }
        if (year == 1109 ) { return false ; }
        if (year == 1110 ) { return false ; }
        if (year == 1111 ) { return false ; }
        if (year == 1112 ) { return true ; }
        if (year == 1113 ) { return false ; }
        if (year == 1114 ) { return false ; }
        if (year == 1115 ) { return false ; }
        if (year == 1116 ) { return true ; }
        if (year == 1117 ) { return false ; }
        if (year == 1118 ) { return false ; }
        if (year == 1119 ) { return false ; }
        if (year == 1120 ) { return true ; }
        if (year == 1121 ) { return false ; }
        if (year == 1122 ) { return false ; }
        if (year == 1123 ) { return false ; }
        if (year == 1124 ) { return true ; }
        if (year == 1125 ) { return false ; }
        if (year == 1126 ) { return false ; }
        if (year == 1127 ) { return false ; }
        if (year == 1128 ) { return true ; }
        if (year == 1129 ) { return false ; }
        if (year == 1130 ) { return false ; }
        if (year == 1131 ) { return false ; }
        if (year == 1132 ) { return true ; }
        if (year == 1133 ) { return false ; }
        if (year == 1134 ) { return false ; }
        if (year == 1135 ) { return false ; }
        if (year == 1136 ) { return true ; }
        if (year == 1137 ) { return false ; }
        if (year == 1138 ) { return false ; }
        if (year == 1139 ) { return false ; }
        if (year == 1140 ) { return true ; }
        if (year == 1141 ) { return false ; }
        if (year == 1142 ) { return false ; }
        if (year == 1143 ) { return false ; }
        if (year == 1144 ) { return true ; }
        if (year == 1145 ) { return false ; }
        if (year == 1146 ) { return false ; }
        if (year == 1147 ) { return false ; }
        if (year == 1148 ) { return true ; }
        if (year == 1149 ) { return false ; }
        if (year == 1150 ) { return false ; }
        if (year == 1151 ) { return false ; }
        if (year == 1152 ) { return true ; }
        if (year == 1153 ) { return false ; }
        if (year == 1154 ) { return false ; }
        if (year == 1155 ) { return false ; }
        if (year == 1156 ) { return true ; }
        if (year == 1157 ) { return false ; }
        if (year == 1158 ) { return false ; }
        if (year == 1159 ) { return false ; }
        if (year == 1160 ) { return true ; }
        if (year == 1161 ) { return false ; }
        if (year == 1162 ) { return false ; }
        if (year == 1163 ) { return false ; }
        if (year == 1164 ) { return true ; }
        if (year == 1165 ) { return false ; }
        if (year == 1166 ) { return false ; }
        if (year == 1167 ) { return false ; }
        if (year == 1168 ) { return true ; }
        if (year == 1169 ) { return false ; }
        if (year == 1170 ) { return false ; }
        if (year == 1171 ) { return false ; }
        if (year == 1172 ) { return true ; }
        if (year == 1173 ) { return false ; }
        if (year == 1174 ) { return false ; }
        if (year == 1175 ) { return false ; }
        if (year == 1176 ) { return true ; }
        if (year == 1177 ) { return false ; }
        if (year == 1178 ) { return false ; }
        if (year == 1179 ) { return false ; }
        if (year == 1180 ) { return true ; }
        if (year == 1181 ) { return false ; }
        if (year == 1182 ) { return false ; }
        if (year == 1183 ) { return false ; }
        if (year == 1184 ) { return true ; }
        if (year == 1185 ) { return false ; }
        if (year == 1186 ) { return false ; }
        if (year == 1187 ) { return false ; }
        if (year == 1188 ) { return true ; }
        if (year == 1189 ) { return false ; }
        if (year == 1190 ) { return false ; }
        if (year == 1191 ) { return false ; }
        if (year == 1192 ) { return true ; }
        if (year == 1193 ) { return false ; }
        if (year == 1194 ) { return false ; }
        if (year == 1195 ) { return false ; }
        if (year == 1196 ) { return true ; }
        if (year == 1197 ) { return false ; }
        if (year == 1198 ) { return false ; }
        if (year == 1199 ) { return false ; }
        if (year == 1200 ) { return true ; }
        if (year == 1201 ) { return false ; }
        if (year == 1202 ) { return false ; }
        if (year == 1203 ) { return false ; }
        if (year == 1204 ) { return true ; }
        if (year == 1205 ) { return false ; }
        if (year == 1206 ) { return false ; }
        if (year == 1207 ) { return false ; }
        if (year == 1208 ) { return true ; }
        if (year == 1209 ) { return false ; }
        if (year == 1210 ) { return false ; }
        if (year == 1211 ) { return false ; }
        if (year == 1212 ) { return true ; }
        if (year == 1213 ) { return false ; }
        if (year == 1214 ) { return false ; }
        if (year == 1215 ) { return false ; }
        if (year == 1216 ) { return true ; }
        if (year == 1217 ) { return false ; }
        if (year == 1218 ) { return false ; }
        if (year == 1219 ) { return false ; }
        if (year == 1220 ) { return true ; }
        if (year == 1221 ) { return false ; }
        if (year == 1222 ) { return false ; }
        if (year == 1223 ) { return false ; }
        if (year == 1224 ) { return true ; }
        if (year == 1225 ) { return false ; }
        if (year == 1226 ) { return false ; }
        if (year == 1227 ) { return false ; }
        if (year == 1228 ) { return true ; }
        if (year == 1229 ) { return false ; }
        if (year == 1230 ) { return false ; }
        if (year == 1231 ) { return false ; }
        if (year == 1232 ) { return true ; }
        if (year == 1233 ) { return false ; }
        if (year == 1234 ) { return false ; }
        if (year == 1235 ) { return false ; }
        if (year == 1236 ) { return true ; }
        if (year == 1237 ) { return false ; }
        if (year == 1238 ) { return false ; }
        if (year == 1239 ) { return false ; }
        if (year == 1240 ) { return true ; }
        if (year == 1241 ) { return false ; }
        if (year == 1242 ) { return false ; }
        if (year == 1243 ) { return false ; }
        if (year == 1244 ) { return true ; }
        if (year == 1245 ) { return false ; }
        if (year == 1246 ) { return false ; }
        if (year == 1247 ) { return false ; }
        if (year == 1248 ) { return true ; }
        if (year == 1249 ) { return false ; }
        if (year == 1250 ) { return false ; }
        if (year == 1251 ) { return false ; }
        if (year == 1252 ) { return true ; }
        if (year == 1253 ) { return false ; }
        if (year == 1254 ) { return false ; }
        if (year == 1255 ) { return false ; }
        if (year == 1256 ) { return true ; }
        if (year == 1257 ) { return false ; }
        if (year == 1258 ) { return false ; }
        if (year == 1259 ) { return false ; }
        if (year == 1260 ) { return true ; }
        if (year == 1261 ) { return false ; }
        if (year == 1262 ) { return false ; }
        if (year == 1263 ) { return false ; }
        if (year == 1264 ) { return true ; }
        if (year == 1265 ) { return false ; }
        if (year == 1266 ) { return false ; }
        if (year == 1267 ) { return false ; }
        if (year == 1268 ) { return true ; }
        if (year == 1269 ) { return false ; }
        if (year == 1270 ) { return false ; }
        if (year == 1271 ) { return false ; }
        if (year == 1272 ) { return true ; }
        if (year == 1273 ) { return false ; }
        if (year == 1274 ) { return false ; }
        if (year == 1275 ) { return false ; }
        if (year == 1276 ) { return true ; }
        if (year == 1277 ) { return false ; }
        if (year == 1278 ) { return false ; }
        if (year == 1279 ) { return false ; }
        if (year == 1280 ) { return true ; }
        if (year == 1281 ) { return false ; }
        if (year == 1282 ) { return false ; }
        if (year == 1283 ) { return false ; }
        if (year == 1284 ) { return true ; }
        if (year == 1285 ) { return false ; }
        if (year == 1286 ) { return false ; }
        if (year == 1287 ) { return false ; }
        if (year == 1288 ) { return true ; }
        if (year == 1289 ) { return false ; }
        if (year == 1290 ) { return false ; }
        if (year == 1291 ) { return false ; }
        if (year == 1292 ) { return true ; }
        if (year == 1293 ) { return false ; }
        if (year == 1294 ) { return false ; }
        if (year == 1295 ) { return false ; }
        if (year == 1296 ) { return true ; }
        if (year == 1297 ) { return false ; }
        if (year == 1298 ) { return false ; }
        if (year == 1299 ) { return false ; }
        if (year == 1300 ) { return false ; }
        if (year == 1301 ) { return false ; }
        if (year == 1302 ) { return false ; }
        if (year == 1303 ) { return false ; }
        if (year == 1304 ) { return true ; }
        if (year == 1305 ) { return false ; }
        if (year == 1306 ) { return false ; }
        if (year == 1307 ) { return false ; }
        if (year == 1308 ) { return true ; }
        if (year == 1309 ) { return false ; }
        if (year == 1310 ) { return false ; }
        if (year == 1311 ) { return false ; }
        if (year == 1312 ) { return true ; }
        if (year == 1313 ) { return false ; }
        if (year == 1314 ) { return false ; }
        if (year == 1315 ) { return false ; }
        if (year == 1316 ) { return true ; }
        if (year == 1317 ) { return false ; }
        if (year == 1318 ) { return false ; }
        if (year == 1319 ) { return false ; }
        if (year == 1320 ) { return true ; }
        if (year == 1321 ) { return false ; }
        if (year == 1322 ) { return false ; }
        if (year == 1323 ) { return false ; }
        if (year == 1324 ) { return true ; }
        if (year == 1325 ) { return false ; }
        if (year == 1326 ) { return false ; }
        if (year == 1327 ) { return false ; }
        if (year == 1328 ) { return true ; }
        if (year == 1329 ) { return false ; }
        if (year == 1330 ) { return false ; }
        if (year == 1331 ) { return false ; }
        if (year == 1332 ) { return true ; }
        if (year == 1333 ) { return false ; }
        if (year == 1334 ) { return false ; }
        if (year == 1335 ) { return false ; }
        if (year == 1336 ) { return true ; }
        if (year == 1337 ) { return false ; }
        if (year == 1338 ) { return false ; }
        if (year == 1339 ) { return false ; }
        if (year == 1340 ) { return true ; }
        if (year == 1341 ) { return false ; }
        if (year == 1342 ) { return false ; }
        if (year == 1343 ) { return false ; }
        if (year == 1344 ) { return true ; }
        if (year == 1345 ) { return false ; }
        if (year == 1346 ) { return false ; }
        if (year == 1347 ) { return false ; }
        if (year == 1348 ) { return true ; }
        if (year == 1349 ) { return false ; }
        if (year == 1350 ) { return false ; }
        if (year == 1351 ) { return false ; }
        if (year == 1352 ) { return true ; }
        if (year == 1353 ) { return false ; }
        if (year == 1354 ) { return false ; }
        if (year == 1355 ) { return false ; }
        if (year == 1356 ) { return true ; }
        if (year == 1357 ) { return false ; }
        if (year == 1358 ) { return false ; }
        if (year == 1359 ) { return false ; }
        if (year == 1360 ) { return true ; }
        if (year == 1361 ) { return false ; }
        if (year == 1362 ) { return false ; }
        if (year == 1363 ) { return false ; }
        if (year == 1364 ) { return true ; }
        if (year == 1365 ) { return false ; }
        if (year == 1366 ) { return false ; }
        if (year == 1367 ) { return false ; }
        if (year == 1368 ) { return true ; }
        if (year == 1369 ) { return false ; }
        if (year == 1370 ) { return false ; }
        if (year == 1371 ) { return false ; }
        if (year == 1372 ) { return true ; }
        if (year == 1373 ) { return false ; }
        if (year == 1374 ) { return false ; }
        if (year == 1375 ) { return false ; }
        if (year == 1376 ) { return true ; }
        if (year == 1377 ) { return false ; }
        if (year == 1378 ) { return false ; }
        if (year == 1379 ) { return false ; }
        if (year == 1380 ) { return true ; }
        if (year == 1381 ) { return false ; }
        if (year == 1382 ) { return false ; }
        if (year == 1383 ) { return false ; }
        if (year == 1384 ) { return true ; }
        if (year == 1385 ) { return false ; }
        if (year == 1386 ) { return false ; }
        if (year == 1387 ) { return false ; }
        if (year == 1388 ) { return true ; }
        if (year == 1389 ) { return false ; }
        if (year == 1390 ) { return false ; }
        if (year == 1391 ) { return false ; }
        if (year == 1392 ) { return true ; }
        if (year == 1393 ) { return false ; }
        if (year == 1394 ) { return false ; }
        if (year == 1395 ) { return false ; }
        if (year == 1396 ) { return true ; }
        if (year == 1397 ) { return false ; }
        if (year == 1398 ) { return false ; }
        if (year == 1399 ) { return false ; }
        if (year == 1400 ) { return false ; }
        if (year == 1401 ) { return false ; }
        if (year == 1402 ) { return false ; }
        if (year == 1403 ) { return false ; }
        if (year == 1404 ) { return true ; }
        if (year == 1405 ) { return false ; }
        if (year == 1406 ) { return false ; }
        if (year == 1407 ) { return false ; }
        if (year == 1408 ) { return true ; }
        if (year == 1409 ) { return false ; }
        if (year == 1410 ) { return false ; }
        if (year == 1411 ) { return false ; }
        if (year == 1412 ) { return true ; }
        if (year == 1413 ) { return false ; }
        if (year == 1414 ) { return false ; }
        if (year == 1415 ) { return false ; }
        if (year == 1416 ) { return true ; }
        if (year == 1417 ) { return false ; }
        if (year == 1418 ) { return false ; }
        if (year == 1419 ) { return false ; }
        if (year == 1420 ) { return true ; }
        if (year == 1421 ) { return false ; }
        if (year == 1422 ) { return false ; }
        if (year == 1423 ) { return false ; }
        if (year == 1424 ) { return true ; }
        if (year == 1425 ) { return false ; }
        if (year == 1426 ) { return false ; }
        if (year == 1427 ) { return false ; }
        if (year == 1428 ) { return true ; }
        if (year == 1429 ) { return false ; }
        if (year == 1430 ) { return false ; }
        if (year == 1431 ) { return false ; }
        if (year == 1432 ) { return true ; }
        if (year == 1433 ) { return false ; }
        if (year == 1434 ) { return false ; }
        if (year == 1435 ) { return false ; }
        if (year == 1436 ) { return true ; }
        if (year == 1437 ) { return false ; }
        if (year == 1438 ) { return false ; }
        if (year == 1439 ) { return false ; }
        if (year == 1440 ) { return true ; }
        if (year == 1441 ) { return false ; }
        if (year == 1442 ) { return false ; }
        if (year == 1443 ) { return false ; }
        if (year == 1444 ) { return true ; }
        if (year == 1445 ) { return false ; }
        if (year == 1446 ) { return false ; }
        if (year == 1447 ) { return false ; }
        if (year == 1448 ) { return true ; }
        if (year == 1449 ) { return false ; }
        if (year == 1450 ) { return false ; }
        if (year == 1451 ) { return false ; }
        if (year == 1452 ) { return true ; }
        if (year == 1453 ) { return false ; }
        if (year == 1454 ) { return false ; }
        if (year == 1455 ) { return false ; }
        if (year == 1456 ) { return true ; }
        if (year == 1457 ) { return false ; }
        if (year == 1458 ) { return false ; }
        if (year == 1459 ) { return false ; }
        if (year == 1460 ) { return true ; }
        if (year == 1461 ) { return false ; }
        if (year == 1462 ) { return false ; }
        if (year == 1463 ) { return false ; }
        if (year == 1464 ) { return true ; }
        if (year == 1465 ) { return false ; }
        if (year == 1466 ) { return false ; }
        if (year == 1467 ) { return false ; }
        if (year == 1468 ) { return true ; }
        if (year == 1469 ) { return false ; }
        if (year == 1470 ) { return false ; }
        if (year == 1471 ) { return false ; }
        if (year == 1472 ) { return true ; }
        if (year == 1473 ) { return false ; }
        if (year == 1474 ) { return false ; }
        if (year == 1475 ) { return false ; }
        if (year == 1476 ) { return true ; }
        if (year == 1477 ) { return false ; }
        if (year == 1478 ) { return false ; }
        if (year == 1479 ) { return false ; }
        if (year == 1480 ) { return true ; }
        if (year == 1481 ) { return false ; }
        if (year == 1482 ) { return false ; }
        if (year == 1483 ) { return false ; }
        if (year == 1484 ) { return true ; }
        if (year == 1485 ) { return false ; }
        if (year == 1486 ) { return false ; }
        if (year == 1487 ) { return false ; }
        if (year == 1488 ) { return true ; }
        if (year == 1489 ) { return false ; }
        if (year == 1490 ) { return false ; }
        if (year == 1491 ) { return false ; }
        if (year == 1492 ) { return true ; }
        if (year == 1493 ) { return false ; }
        if (year == 1494 ) { return false ; }
        if (year == 1495 ) { return false ; }
        if (year == 1496 ) { return true ; }
        if (year == 1497 ) { return false ; }
        if (year == 1498 ) { return false ; }
        if (year == 1499 ) { return false ; }
        if (year == 1500 ) { return false ; }
        if (year == 1501 ) { return false ; }
        if (year == 1502 ) { return false ; }
        if (year == 1503 ) { return false ; }
        if (year == 1504 ) { return true ; }
        if (year == 1505 ) { return false ; }
        if (year == 1506 ) { return false ; }
        if (year == 1507 ) { return false ; }
        if (year == 1508 ) { return true ; }
        if (year == 1509 ) { return false ; }
        if (year == 1510 ) { return false ; }
        if (year == 1511 ) { return false ; }
        if (year == 1512 ) { return true ; }
        if (year == 1513 ) { return false ; }
        if (year == 1514 ) { return false ; }
        if (year == 1515 ) { return false ; }
        if (year == 1516 ) { return true ; }
        if (year == 1517 ) { return false ; }
        if (year == 1518 ) { return false ; }
        if (year == 1519 ) { return false ; }
        if (year == 1520 ) { return true ; }
        if (year == 1521 ) { return false ; }
        if (year == 1522 ) { return false ; }
        if (year == 1523 ) { return false ; }
        if (year == 1524 ) { return true ; }
        if (year == 1525 ) { return false ; }
        if (year == 1526 ) { return false ; }
        if (year == 1527 ) { return false ; }
        if (year == 1528 ) { return true ; }
        if (year == 1529 ) { return false ; }
        if (year == 1530 ) { return false ; }
        if (year == 1531 ) { return false ; }
        if (year == 1532 ) { return true ; }
        if (year == 1533 ) { return false ; }
        if (year == 1534 ) { return false ; }
        if (year == 1535 ) { return false ; }
        if (year == 1536 ) { return true ; }
        if (year == 1537 ) { return false ; }
        if (year == 1538 ) { return false ; }
        if (year == 1539 ) { return false ; }
        if (year == 1540 ) { return true ; }
        if (year == 1541 ) { return false ; }
        if (year == 1542 ) { return false ; }
        if (year == 1543 ) { return false ; }
        if (year == 1544 ) { return true ; }
        if (year == 1545 ) { return false ; }
        if (year == 1546 ) { return false ; }
        if (year == 1547 ) { return false ; }
        if (year == 1548 ) { return true ; }
        if (year == 1549 ) { return false ; }
        if (year == 1550 ) { return false ; }
        if (year == 1551 ) { return false ; }
        if (year == 1552 ) { return true ; }
        if (year == 1553 ) { return false ; }
        if (year == 1554 ) { return false ; }
        if (year == 1555 ) { return false ; }
        if (year == 1556 ) { return true ; }
        if (year == 1557 ) { return false ; }
        if (year == 1558 ) { return false ; }
        if (year == 1559 ) { return false ; }
        if (year == 1560 ) { return true ; }
        if (year == 1561 ) { return false ; }
        if (year == 1562 ) { return false ; }
        if (year == 1563 ) { return false ; }
        if (year == 1564 ) { return true ; }
        if (year == 1565 ) { return false ; }
        if (year == 1566 ) { return false ; }
        if (year == 1567 ) { return false ; }
        if (year == 1568 ) { return true ; }
        if (year == 1569 ) { return false ; }
        if (year == 1570 ) { return false ; }
        if (year == 1571 ) { return false ; }
        if (year == 1572 ) { return true ; }
        if (year == 1573 ) { return false ; }
        if (year == 1574 ) { return false ; }
        if (year == 1575 ) { return false ; }
        if (year == 1576 ) { return true ; }
        if (year == 1577 ) { return false ; }
        if (year == 1578 ) { return false ; }
        if (year == 1579 ) { return false ; }
        if (year == 1580 ) { return true ; }
        if (year == 1581 ) { return false ; }
        if (year == 1582 ) { return false ; }
        if (year == 1583 ) { return false ; }
        if (year == 1584 ) { return true ; }
        if (year == 1585 ) { return false ; }
        if (year == 1586 ) { return false ; }
        if (year == 1587 ) { return false ; }
        if (year == 1588 ) { return true ; }
        if (year == 1589 ) { return false ; }
        if (year == 1590 ) { return false ; }
        if (year == 1591 ) { return false ; }
        if (year == 1592 ) { return true ; }
        if (year == 1593 ) { return false ; }
        if (year == 1594 ) { return false ; }
        if (year == 1595 ) { return false ; }
        if (year == 1596 ) { return true ; }
        if (year == 1597 ) { return false ; }
        if (year == 1598 ) { return false ; }
        if (year == 1599 ) { return false ; }
        if (year == 1600 ) { return true ; }
        if (year == 1601 ) { return false ; }
        if (year == 1602 ) { return false ; }
        if (year == 1603 ) { return false ; }
        if (year == 1604 ) { return true ; }
        if (year == 1605 ) { return false ; }
        if (year == 1606 ) { return false ; }
        if (year == 1607 ) { return false ; }
        if (year == 1608 ) { return true ; }
        if (year == 1609 ) { return false ; }
        if (year == 1610 ) { return false ; }
        if (year == 1611 ) { return false ; }
        if (year == 1612 ) { return true ; }
        if (year == 1613 ) { return false ; }
        if (year == 1614 ) { return false ; }
        if (year == 1615 ) { return false ; }
        if (year == 1616 ) { return true ; }
        if (year == 1617 ) { return false ; }
        if (year == 1618 ) { return false ; }
        if (year == 1619 ) { return false ; }
        if (year == 1620 ) { return true ; }
        if (year == 1621 ) { return false ; }
        if (year == 1622 ) { return false ; }
        if (year == 1623 ) { return false ; }
        if (year == 1624 ) { return true ; }
        if (year == 1625 ) { return false ; }
        if (year == 1626 ) { return false ; }
        if (year == 1627 ) { return false ; }
        if (year == 1628 ) { return true ; }
        if (year == 1629 ) { return false ; }
        if (year == 1630 ) { return false ; }
        if (year == 1631 ) { return false ; }
        if (year == 1632 ) { return true ; }
        if (year == 1633 ) { return false ; }
        if (year == 1634 ) { return false ; }
        if (year == 1635 ) { return false ; }
        if (year == 1636 ) { return true ; }
        if (year == 1637 ) { return false ; }
        if (year == 1638 ) { return false ; }
        if (year == 1639 ) { return false ; }
        if (year == 1640 ) { return true ; }
        if (year == 1641 ) { return false ; }
        if (year == 1642 ) { return false ; }
        if (year == 1643 ) { return false ; }
        if (year == 1644 ) { return true ; }
        if (year == 1645 ) { return false ; }
        if (year == 1646 ) { return false ; }
        if (year == 1647 ) { return false ; }
        if (year == 1648 ) { return true ; }
        if (year == 1649 ) { return false ; }
        if (year == 1650 ) { return false ; }
        if (year == 1651 ) { return false ; }
        if (year == 1652 ) { return true ; }
        if (year == 1653 ) { return false ; }
        if (year == 1654 ) { return false ; }
        if (year == 1655 ) { return false ; }
        if (year == 1656 ) { return true ; }
        if (year == 1657 ) { return false ; }
        if (year == 1658 ) { return false ; }
        if (year == 1659 ) { return false ; }
        if (year == 1660 ) { return true ; }
        if (year == 1661 ) { return false ; }
        if (year == 1662 ) { return false ; }
        if (year == 1663 ) { return false ; }
        if (year == 1664 ) { return true ; }
        if (year == 1665 ) { return false ; }
        if (year == 1666 ) { return false ; }
        if (year == 1667 ) { return false ; }
        if (year == 1668 ) { return true ; }
        if (year == 1669 ) { return false ; }
        if (year == 1670 ) { return false ; }
        if (year == 1671 ) { return false ; }
        if (year == 1672 ) { return true ; }
        if (year == 1673 ) { return false ; }
        if (year == 1674 ) { return false ; }
        if (year == 1675 ) { return false ; }
        if (year == 1676 ) { return true ; }
        if (year == 1677 ) { return false ; }
        if (year == 1678 ) { return false ; }
        if (year == 1679 ) { return false ; }
        if (year == 1680 ) { return true ; }
        if (year == 1681 ) { return false ; }
        if (year == 1682 ) { return false ; }
        if (year == 1683 ) { return false ; }
        if (year == 1684 ) { return true ; }
        if (year == 1685 ) { return false ; }
        if (year == 1686 ) { return false ; }
        if (year == 1687 ) { return false ; }
        if (year == 1688 ) { return true ; }
        if (year == 1689 ) { return false ; }
        if (year == 1690 ) { return false ; }
        if (year == 1691 ) { return false ; }
        if (year == 1692 ) { return true ; }
        if (year == 1693 ) { return false ; }
        if (year == 1694 ) { return false ; }
        if (year == 1695 ) { return false ; }
        if (year == 1696 ) { return true ; }
        if (year == 1697 ) { return false ; }
        if (year == 1698 ) { return false ; }
        if (year == 1699 ) { return false ; }
        if (year == 1700 ) { return false ; }
        if (year == 1701 ) { return false ; }
        if (year == 1702 ) { return false ; }
        if (year == 1703 ) { return false ; }
        if (year == 1704 ) { return true ; }
        if (year == 1705 ) { return false ; }
        if (year == 1706 ) { return false ; }
        if (year == 1707 ) { return false ; }
        if (year == 1708 ) { return true ; }
        if (year == 1709 ) { return false ; }
        if (year == 1710 ) { return false ; }
        if (year == 1711 ) { return false ; }
        if (year == 1712 ) { return true ; }
        if (year == 1713 ) { return false ; }
        if (year == 1714 ) { return false ; }
        if (year == 1715 ) { return false ; }
        if (year == 1716 ) { return true ; }
        if (year == 1717 ) { return false ; }
        if (year == 1718 ) { return false ; }
        if (year == 1719 ) { return false ; }
        if (year == 1720 ) { return true ; }
        if (year == 1721 ) { return false ; }
        if (year == 1722 ) { return false ; }
        if (year == 1723 ) { return false ; }
        if (year == 1724 ) { return true ; }
        if (year == 1725 ) { return false ; }
        if (year == 1726 ) { return false ; }
        if (year == 1727 ) { return false ; }
        if (year == 1728 ) { return true ; }
        if (year == 1729 ) { return false ; }
        if (year == 1730 ) { return false ; }
        if (year == 1731 ) { return false ; }
        if (year == 1732 ) { return true ; }
        if (year == 1733 ) { return false ; }
        if (year == 1734 ) { return false ; }
        if (year == 1735 ) { return false ; }
        if (year == 1736 ) { return true ; }
        if (year == 1737 ) { return false ; }
        if (year == 1738 ) { return false ; }
        if (year == 1739 ) { return false ; }
        if (year == 1740 ) { return true ; }
        if (year == 1741 ) { return false ; }
        if (year == 1742 ) { return false ; }
        if (year == 1743 ) { return false ; }
        if (year == 1744 ) { return true ; }
        if (year == 1745 ) { return false ; }
        if (year == 1746 ) { return false ; }
        if (year == 1747 ) { return false ; }
        if (year == 1748 ) { return true ; }
        if (year == 1749 ) { return false ; }
        if (year == 1750 ) { return false ; }
        if (year == 1751 ) { return false ; }
        if (year == 1752 ) { return true ; }
        if (year == 1753 ) { return false ; }
        if (year == 1754 ) { return false ; }
        if (year == 1755 ) { return false ; }
        if (year == 1756 ) { return true ; }
        if (year == 1757 ) { return false ; }
        if (year == 1758 ) { return false ; }
        if (year == 1759 ) { return false ; }
        if (year == 1760 ) { return true ; }
        if (year == 1761 ) { return false ; }
        if (year == 1762 ) { return false ; }
        if (year == 1763 ) { return false ; }
        if (year == 1764 ) { return true ; }
        if (year == 1765 ) { return false ; }
        if (year == 1766 ) { return false ; }
        if (year == 1767 ) { return false ; }
        if (year == 1768 ) { return true ; }
        if (year == 1769 ) { return false ; }
        if (year == 1770 ) { return false ; }
        if (year == 1771 ) { return false ; }
        if (year == 1772 ) { return true ; }
        if (year == 1773 ) { return false ; }
        if (year == 1774 ) { return false ; }
        if (year == 1775 ) { return false ; }
        if (year == 1776 ) { return true ; }
        if (year == 1777 ) { return false ; }
        if (year == 1778 ) { return false ; }
        if (year == 1779 ) { return false ; }
        if (year == 1780 ) { return true ; }
        if (year == 1781 ) { return false ; }
        if (year == 1782 ) { return false ; }
        if (year == 1783 ) { return false ; }
        if (year == 1784 ) { return true ; }
        if (year == 1785 ) { return false ; }
        if (year == 1786 ) { return false ; }
        if (year == 1787 ) { return false ; }
        if (year == 1788 ) { return true ; }
        if (year == 1789 ) { return false ; }
        if (year == 1790 ) { return false ; }
        if (year == 1791 ) { return false ; }
        if (year == 1792 ) { return true ; }
        if (year == 1793 ) { return false ; }
        if (year == 1794 ) { return false ; }
        if (year == 1795 ) { return false ; }
        if (year == 1796 ) { return true ; }
        if (year == 1797 ) { return false ; }
        if (year == 1798 ) { return false ; }
        if (year == 1799 ) { return false ; }
        if (year == 1800 ) { return false ; }
        if (year == 1801 ) { return false ; }
        if (year == 1802 ) { return false ; }
        if (year == 1803 ) { return false ; }
        if (year == 1804 ) { return true ; }
        if (year == 1805 ) { return false ; }
        if (year == 1806 ) { return false ; }
        if (year == 1807 ) { return false ; }
        if (year == 1808 ) { return true ; }
        if (year == 1809 ) { return false ; }
        if (year == 1810 ) { return false ; }
        if (year == 1811 ) { return false ; }
        if (year == 1812 ) { return true ; }
        if (year == 1813 ) { return false ; }
        if (year == 1814 ) { return false ; }
        if (year == 1815 ) { return false ; }
        if (year == 1816 ) { return true ; }
        if (year == 1817 ) { return false ; }
        if (year == 1818 ) { return false ; }
        if (year == 1819 ) { return false ; }
        if (year == 1820 ) { return true ; }
        if (year == 1821 ) { return false ; }
        if (year == 1822 ) { return false ; }
        if (year == 1823 ) { return false ; }
        if (year == 1824 ) { return true ; }
        if (year == 1825 ) { return false ; }
        if (year == 1826 ) { return false ; }
        if (year == 1827 ) { return false ; }
        if (year == 1828 ) { return true ; }
        if (year == 1829 ) { return false ; }
        if (year == 1830 ) { return false ; }
        if (year == 1831 ) { return false ; }
        if (year == 1832 ) { return true ; }
        if (year == 1833 ) { return false ; }
        if (year == 1834 ) { return false ; }
        if (year == 1835 ) { return false ; }
        if (year == 1836 ) { return true ; }
        if (year == 1837 ) { return false ; }
        if (year == 1838 ) { return false ; }
        if (year == 1839 ) { return false ; }
        if (year == 1840 ) { return true ; }
        if (year == 1841 ) { return false ; }
        if (year == 1842 ) { return false ; }
        if (year == 1843 ) { return false ; }
        if (year == 1844 ) { return true ; }
        if (year == 1845 ) { return false ; }
        if (year == 1846 ) { return false ; }
        if (year == 1847 ) { return false ; }
        if (year == 1848 ) { return true ; }
        if (year == 1849 ) { return false ; }
        if (year == 1850 ) { return false ; }
        if (year == 1851 ) { return false ; }
        if (year == 1852 ) { return true ; }
        if (year == 1853 ) { return false ; }
        if (year == 1854 ) { return false ; }
        if (year == 1855 ) { return false ; }
        if (year == 1856 ) { return true ; }
        if (year == 1857 ) { return false ; }
        if (year == 1858 ) { return false ; }
        if (year == 1859 ) { return false ; }
        if (year == 1860 ) { return true ; }
        if (year == 1861 ) { return false ; }
        if (year == 1862 ) { return false ; }
        if (year == 1863 ) { return false ; }
        if (year == 1864 ) { return true ; }
        if (year == 1865 ) { return false ; }
        if (year == 1866 ) { return false ; }
        if (year == 1867 ) { return false ; }
        if (year == 1868 ) { return true ; }
        if (year == 1869 ) { return false ; }
        if (year == 1870 ) { return false ; }
        if (year == 1871 ) { return false ; }
        if (year == 1872 ) { return true ; }
        if (year == 1873 ) { return false ; }
        if (year == 1874 ) { return false ; }
        if (year == 1875 ) { return false ; }
        if (year == 1876 ) { return true ; }
        if (year == 1877 ) { return false ; }
        if (year == 1878 ) { return false ; }
        if (year == 1879 ) { return false ; }
        if (year == 1880 ) { return true ; }
        if (year == 1881 ) { return false ; }
        if (year == 1882 ) { return false ; }
        if (year == 1883 ) { return false ; }
        if (year == 1884 ) { return true ; }
        if (year == 1885 ) { return false ; }
        if (year == 1886 ) { return false ; }
        if (year == 1887 ) { return false ; }
        if (year == 1888 ) { return true ; }
        if (year == 1889 ) { return false ; }
        if (year == 1890 ) { return false ; }
        if (year == 1891 ) { return false ; }
        if (year == 1892 ) { return true ; }
        if (year == 1893 ) { return false ; }
        if (year == 1894 ) { return false ; }
        if (year == 1895 ) { return false ; }
        if (year == 1896 ) { return true ; }
        if (year == 1897 ) { return false ; }
        if (year == 1898 ) { return false ; }
        if (year == 1899 ) { return false ; }
        if (year == 1900 ) { return false ; }
        if (year == 1901 ) { return false ; }
        if (year == 1902 ) { return false ; }
        if (year == 1903 ) { return false ; }
        if (year == 1904 ) { return true ; }
        if (year == 1905 ) { return false ; }
        if (year == 1906 ) { return false ; }
        if (year == 1907 ) { return false ; }
        if (year == 1908 ) { return true ; }
        if (year == 1909 ) { return false ; }
        if (year == 1910 ) { return false ; }
        if (year == 1911 ) { return false ; }
        if (year == 1912 ) { return true ; }
        if (year == 1913 ) { return false ; }
        if (year == 1914 ) { return false ; }
        if (year == 1915 ) { return false ; }
        if (year == 1916 ) { return true ; }
        if (year == 1917 ) { return false ; }
        if (year == 1918 ) { return false ; }
        if (year == 1919 ) { return false ; }
        if (year == 1920 ) { return true ; }
        if (year == 1921 ) { return false ; }
        if (year == 1922 ) { return false ; }
        if (year == 1923 ) { return false ; }
        if (year == 1924 ) { return true ; }
        if (year == 1925 ) { return false ; }
        if (year == 1926 ) { return false ; }
        if (year == 1927 ) { return false ; }
        if (year == 1928 ) { return true ; }
        if (year == 1929 ) { return false ; }
        if (year == 1930 ) { return false ; }
        if (year == 1931 ) { return false ; }
        if (year == 1932 ) { return true ; }
        if (year == 1933 ) { return false ; }
        if (year == 1934 ) { return false ; }
        if (year == 1935 ) { return false ; }
        if (year == 1936 ) { return true ; }
        if (year == 1937 ) { return false ; }
        if (year == 1938 ) { return false ; }
        if (year == 1939 ) { return false ; }
        if (year == 1940 ) { return true ; }
        if (year == 1941 ) { return false ; }
        if (year == 1942 ) { return false ; }
        if (year == 1943 ) { return false ; }
        if (year == 1944 ) { return true ; }
        if (year == 1945 ) { return false ; }
        if (year == 1946 ) { return false ; }
        if (year == 1947 ) { return false ; }
        if (year == 1948 ) { return true ; }
        if (year == 1949 ) { return false ; }
        if (year == 1950 ) { return false ; }
        if (year == 1951 ) { return false ; }
        if (year == 1952 ) { return true ; }
        if (year == 1953 ) { return false ; }
        if (year == 1954 ) { return false ; }
        if (year == 1955 ) { return false ; }
        if (year == 1956 ) { return true ; }
        if (year == 1957 ) { return false ; }
        if (year == 1958 ) { return false ; }
        if (year == 1959 ) { return false ; }
        if (year == 1960 ) { return true ; }
        if (year == 1961 ) { return false ; }
        if (year == 1962 ) { return false ; }
        if (year == 1963 ) { return false ; }
        if (year == 1964 ) { return true ; }
        if (year == 1965 ) { return false ; }
        if (year == 1966 ) { return false ; }
        if (year == 1967 ) { return false ; }
        if (year == 1968 ) { return true ; }
        if (year == 1969 ) { return false ; }
        if (year == 1970 ) { return false ; }
        if (year == 1971 ) { return false ; }
        if (year == 1972 ) { return true ; }
        if (year == 1973 ) { return false ; }
        if (year == 1974 ) { return false ; }
        if (year == 1975 ) { return false ; }
        if (year == 1976 ) { return true ; }
        if (year == 1977 ) { return false ; }
        if (year == 1978 ) { return false ; }
        if (year == 1979 ) { return false ; }
        if (year == 1980 ) { return true ; }
        if (year == 1981 ) { return false ; }
        if (year == 1982 ) { return false ; }
        if (year == 1983 ) { return false ; }
        if (year == 1984 ) { return true ; }
        if (year == 1985 ) { return false ; }
        if (year == 1986 ) { return false ; }
        if (year == 1987 ) { return false ; }
        if (year == 1988 ) { return true ; }
        if (year == 1989 ) { return false ; }
        if (year == 1990 ) { return false ; }
        if (year == 1991 ) { return false ; }
        if (year == 1992 ) { return true ; }
        if (year == 1993 ) { return false ; }
        if (year == 1994 ) { return false ; }
        if (year == 1995 ) { return false ; }
        if (year == 1996 ) { return true ; }
        if (year == 1997 ) { return false ; }
        if (year == 1998 ) { return false ; }
        if (year == 1999 ) { return false ; }
        if (year == 2000 ) { return true ; }
        if (year == 2001 ) { return false ; }
        if (year == 2002 ) { return false ; }
        if (year == 2003 ) { return false ; }
        if (year == 2004 ) { return true ; }
        if (year == 2005 ) { return false ; }
        if (year == 2006 ) { return false ; }
        if (year == 2007 ) { return false ; }
        if (year == 2008 ) { return true ; }
        if (year == 2009 ) { return false ; }
        if (year == 2010 ) { return false ; }
        if (year == 2011 ) { return false ; }
        if (year == 2012 ) { return true ; }
        if (year == 2013 ) { return false ; }
        if (year == 2014 ) { return false ; }
        if (year == 2015 ) { return false ; }
        if (year == 2016 ) { return true ; }
        if (year == 2017 ) { return false ; }
        if (year == 2018 ) { return false ; }
        if (year == 2019 ) { return false ; }
        if (year == 2020 ) { return true ; }
        if (year == 2021 ) { return false ; }
        if (year == 2022 ) { return false ; }
        if (year == 2023 ) { return false ; }
        if (year == 2024 ) { return true ; }

        return false;
    }
}
